const Types = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  CLEAR_USER: 'CLEAR_USER',
  LOGIN: 'LOGIN',
  SPLASH: 'SPLASH',
  SECRET_KEY: 'SECRET_KEY',
  REMEMBER_KEY: 'REMEMBER_KEY',
  TOGGLE_PATIENT: "TOGGLE_PATIENT"

};

export default Types;
